@baseUrl = http://localhost:8000

POST {{baseUrl}}/comments
Content-Type: application/json

{
    "firstName": "http",
    "lastName": "wow"
}

###

GET {{baseUrl}}/comments

###

POST {{baseUrl}}/comments